// RestApi_Client/ServerSideGrouping/react/src/app.jsx
import 'bootstrap.css';
import '@mescius/wijmo.styles/wijmo.css';
import ReactDOM from 'react-dom/client';
import React, { useRef, useState } from 'react';
import { FlexGrid, FlexGridColumn } from '@mescius/wijmo.react.grid';
import { FlexGridFilter } from '@mescius/wijmo.react.grid.filter';
import { RestGroupCollectionView } from './rest-group-collection-view';
import { createElement } from '@mescius/wijmo';
import './app.css';
// field info for PurchaseOrders table
const fields = 'OrderId,StockItem,Color,State,City,Quantity,UnitPrice,Date,IsChillerStock'.split(',');
function App() {
    const [selectedFeature, setSelectedFeature] = useState('groupServer');
    const [isReadOnly, setIsReadOnly] = useState(true);
    const _isFirstLoad = useRef(true);
    const flexRef = useRef(null);
    const flexInitialized = (flexgrid) => {
        flexRef.current = flexgrid;
        //create RestGroupCollectionView instance 
        //with settings for default server grouping on first load
        flexRef.current.itemsSource = new RestGroupCollectionView('purchaseorders', settings);
    };
    const settings = {
        fields: fields,
        virtualization: false,
        groupLazyLoading: false,
        groupDescriptions: ['State', 'City'],
        loading: () => { toggleSpinner(flexRef.current, true); },
        loaded: (s, e) => {
            toggleSpinner(flexRef.current, false);
            if (_isFirstLoad.current) {
                _isFirstLoad.current = false;
                // select first group row 
                setTimeout(() => {
                    flexRef.current.select(0, 0);
                });
            }
        }
    };
    const toggleFeature = (feature) => {
        setSelectedFeature(feature);
        _isFirstLoad.current = true;
        //default server group
        if (feature == "groupServer") {
            settings.virtualization = false;
            settings.groupLazyLoading = false;
        }
        // enable virtualization
        if (feature == "virtual") {
            settings.virtualization = true;
            settings.groupLazyLoading = false;
        }
        //enable group lazy loading
        if (feature == "lazyload") {
            settings.virtualization = false;
            settings.groupLazyLoading = true;
        }
        // reset itemsSource    
        flexRef.current.itemsSource = new RestGroupCollectionView('purchaseorders', settings);
    };
    return (<div className="container-fluid">
      <div id="feature-options">
        <label htmlFor="groupServer">
          <input id="groupServer" type="radio" name="feature" value="groupOnServer" checked={selectedFeature === 'groupServer'} onChange={() => toggleFeature('groupServer')}/>{' '}
          Server Side Grouping
        </label>
        <br />
        <label htmlFor="virtual">
          <input id="virtual" type="radio" name="feature" value="virtualGrouping" onChange={() => toggleFeature('virtual')}/>{' '}
          Server Side Grouping with virtualization
        </label>
        <br />
        <label htmlFor="lazyload">
          <input id="lazyload" type="radio" name="feature" value="lazyLoadGrouping" onChange={() => toggleFeature('lazyload')}/>{' '}
          Server Side Grouping with group lazy-loading
        </label>
      </div>

      <br />

      <FlexGrid initialized={flexInitialized} isReadOnly={isReadOnly} autoGenerateColumns={false}>
        <FlexGridFilter defaultFilterType="Condition"/>
        <FlexGridColumn binding="OrderId" header="Order ID"/>
        <FlexGridColumn binding="StockItem" header="Stock Item" width="*" minWidth={200}/>
        <FlexGridColumn binding="Color" header="Color"/>
        <FlexGridColumn binding="Quantity" header="Quantity" dataType="Number" format="n0"/>
        <FlexGridColumn binding="UnitPrice" header="Unit Price" dataType="Number" format="n2"/>
        <FlexGridColumn binding="Date" header="Date" dataType="Date" format="d"/>
        <FlexGridColumn binding="IsChillerStock" header="Is Chiller Stock" dataType="Boolean"/>
      </FlexGrid>
    </div>);
}
//show gif loader while data loading
function toggleSpinner(grid, show) {
    let _rect = grid.controlRect;
    let elem = grid.hostElement.querySelector('.spinner');
    if (!elem)
        elem = createElement(`<div class='spinner' style="left:${_rect.left}px;top:${_rect.top}px;width:${_rect.width}px;height:${_rect.height}px;"><img src="resources/Rounded%20blocks.gif"></div>`, grid.hostElement);
    elem.style.display = show ? 'block' : 'none';
}
const container = document.getElementById('app');
if (container) {
    const root = ReactDOM.createRoot(container);
    root.render(<App />);
}

// RestApi_Client/ServerSideGrouping/vue/src/app.vue
<template>
    <div class="container-fluid">
        <div id="feature-options">
            <label for="groupServer">
                <input id="groupServer" type="radio" name="feature" value="groupOnServer" checked
                    v-model="selectedFeature" @change="toggleFeature('groupServer')" />
                Server Side Grouping
            </label>
            <br />
            <label for="virtual">
                <input id="virtual" type="radio" name="feature" value="virtualGrouping"
                    @change="toggleFeature('virtual')" />
                Server Side Grouping with virtualization
            </label>
            <br />
            <label for="lazyload">
                <input id="lazyload" type="radio" name="feature" value="lazyLoadGrouping"
                    @change="toggleFeature('lazyload')" />
                Server Side Grouping with group lazy-loading
            </label>
        </div>

        <br />

        <wj-flex-grid :initialized="flexInitialized" :itemsSource="view" :isReadOnly="isReadOnly"
            :autoGenerateColumns="false">
            <wj-flex-grid-filter :defaultFilterType="'Condition'" />
            <wj-flex-grid-column binding="OrderId" header="Order ID" />
            <wj-flex-grid-column binding="StockItem" header="Stock Item" :width="'*'" :minWidth="200" />
            <wj-flex-grid-column binding="Color" header="Color" />
            <wj-flex-grid-column binding="Quantity" header="Quantity" :dataType="'Number'" format="n0" />
            <wj-flex-grid-column binding="UnitPrice" header="Unit Price" :dataType="'Number'" format="n2" />
            <wj-flex-grid-column binding="Date" header="Date" :dataType="'Date'" format="d" />
            <wj-flex-grid-column binding="IsChillerStock" header="Is Chiller Stock" :dataType="'Boolean'" />
        </wj-flex-grid>
    </div>
</template>
<script>
import 'bootstrap.css';
import '@mescius/wijmo.styles/wijmo.css';
//
import { createApp } from "vue"
import { registerGrid } from "@mescius/wijmo.vue2.grid";
import { registerGridFilter } from "@mescius/wijmo.vue2.grid.filter";
import { registerInput } from "@mescius/wijmo.vue2.input";
import { RestGroupCollectionView } from './rest-group-collection-view';
// field info for PurchaseOrders table
const fields = 'OrderId,StockItem,Color,State,City,Quantity,UnitPrice,Date,IsChillerStock'.split(',');
//
let App = {
    name: "App",
    created: function () {
        //create RestGroupCollectionView instance 
        //with settings for default server grouping on first load
        this.view = new RestGroupCollectionView('purchaseorders', this.settings)
    },
    data: function () {
        return {
            isReadOnly: true,
            _isFirstLoad: true,
            settings: {
                fields: fields,
                virtualization: false,
                groupLazyLoading: false,
                groupDescriptions: ['State', 'City'],
                loading: () => { this.toggleSpinner(this.flexGrid, true); },
                loaded: (s, e) => {
                    this.toggleSpinner(this.flexGrid, false);
                    if (this._isFirstLoad) {
                        this._isFirstLoad = false;
                        // select first group row 
                        setTimeout(() => {
                            this.flexGrid.select(0, 0);
                        })
                    }
                }
            }
        }
    },
    methods: {
        flexInitialized(grid) {
            this.flexGrid = grid;
        },
        toggleFeature(feature) {
            this.selectedFeature = feature;
            this._isFirstLoad = true;
            if (feature === 'groupServer') {
                this.settings.virtualization = false;
                this.settings.groupLazyLoading = false;
            } else if (feature === 'virtual') {
                this.settings.virtualization = true;
                this.settings.groupLazyLoading = false;
            } else if (feature === 'lazyload') {
                this.settings.virtualization = false;
                this.settings.groupLazyLoading = true;
            }
            this.flexGrid.itemsSource = new RestGroupCollectionView('purchaseorders', this.settings);
        },
        //show gif loader while data loading
        toggleSpinner(grid, show) {
            let _rect = grid.controlRect;
            let elem = grid.hostElement.querySelector('.spinner');
            if (!elem)
                elem = wijmo.createElement(`<div class='spinner' style="left:${_rect.left}px;top:${_rect.top}px;width:${_rect.width}px;height:${_rect.height}px;"><img src="resources/Rounded%20blocks.gif"></div>`, grid.hostElement);
            elem.style.display = show ? 'block' : 'none';
        }
    }
};

const app = createApp(App);
// register all components and directives from Wijmo modules
registerInput(app);
registerGrid(app);
registerGridFilter(app);
app.mount('#app');

</script>

<style>
body {
    margin-bottom: 36pt;
    margin-top: 10px;
}

.wj-flexgrid {
    height: 400px;
}

.spinner {
    position: absolute;
    z-index: 10;
    opacity: .5;
}

.spinner img {
    margin: auto;
    position: relative;
    top: 40%;
    left: 45%;
}
</style>
